### ISSUE TITLE
Support for unverified SSL

### ISSUE THREAD

**Issue by jaxxstorm** [murraju/ucslib#7]
Is there any chance that support for request URI's that use SSL but have unverified certs can be added?

I tried to add myself, but it seems that my ruby knowledge isn't good enough :(

**Comment by nctiggy** [comment]
My latest pull request should address this quite nicely. When creating your JSON to initialize the object include :verify_ssl => "false"  like below

authjson = { :username => 'admin', :password => 'admin', :ip => '172.16.192.175', :verify_ssl => "false"}.to_json

**Comment by murraju** [comment]
Closing this one based on latest pull from Craig.
